name: Release with Artifact

on:
  release:
    types: [published]

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Zip source files
        run: zip -r release-${{ github.ref_name }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-archive
          path: release-${{ github.ref_name }}.zip