name: Trigger on Release

on:
  release:
    types: [published]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show release info
        run: echo "A new release was published"